Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -25,12 +25,25 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: "20"
+          node-version: "14"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
       - name: Setup Pages
         uses: actions/configure-pages@v5
         with:
           static_site_generator: next
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+          elif [ -f "package-lock.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Restore cache
         uses: actions/cache@v4
         with:
@@ -48,6 +61,7 @@ jobs:
         with:
           name: nextjs-build
           path: .next
+        
 
   deploy:
     environment:
